accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from .views import RegisterFormView

urlpatterns = [
    path('register/', RegisterFormView.as_view(), name='register'),
]

cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('admin/', admin.site.urls),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('shop/', include(('shop.urls', 'shop'), namespace='shop')),
    path('account/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/shop/', permanent=True)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from django.conf.urls import url
from shop import views

#
# urlpatterns = [
#     path("", views.index, name='index'),
# ]

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True, unique=True)

    class Meta:
        ordering = ("name",)
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                        args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(
        Category,
        related_name="product",
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=200, db_index=True)
    image = models.ImageField(upload_to="products/%Y/%m/%d", blank=True)
    thumbnail = models.ImageField(upload_to="products/%Y/%m/%d", blank=True, null=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=20, decimal_places=2)
    available = models.BooleanField(default=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("name",)

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

    def __str__(self):
        return self.name


class Comment(models.Model):
    product = models.ForeignKey(
        Product,
        related_name="comments",
        on_delete=models.CASCADE,
    )
    name = models.CharField(max_length=200)
    text = models.TextField()
    approved = models.BooleanField(default=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("create_date",)

    def approve(self):
        self.approved = True
        self.save()

    def __str__(self):
        return self.text

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    context = {'category': category,
               'categories': categories,
               'products': products}

    return render(request, 'shop/product/list.html', context=context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)

    cart_form = CartAddProductForm()
    context = {'product': product, 'cart_product_form': cart_form}

    return render(request, 'shop/product/detail.html', context=context)

shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}My shop{% endblock %}</title>
    <link href="{% static "css/styles.css" %}" rel="stylesheet">
    <style>
        a {
            padding: 10px 10px;
            color: black;
        }
    </style>
</head>
<body>
<div id="header">
    <a href="/" class="logo">My shop</a>

    <div style="display: block; float: right;">
        {% if user.is_authenticated %}
            <a href="{% url 'logout' %}">Log Out({{ user.username }})</a>
        {% else %}
            <a href="{% url 'accounts:register' %}">Sign Up</a>
            <a href="{% url 'login' %}">Sign In</a>
        {% endif %}
    </div>
</div>

<div id="subheader">
    <div class="cart">
        {% with total_items=cart|length %}
            {% if cart|length > 0 %}
                Your cart:
                <a href="{% url "cart:cart_detail" %}">
                    {{ total_items }} item{{ total_items|pluralize }}, ${{ cart.get_total_price }}
                </a>
            {% else %}
                Your cart is empty.
            {% endif %}
        {% endwith %}
    </div>
</div>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>